name: Build & Push Image to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  docker:
    runs-on: ubuntu-latest

    steps: 
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
        - name: Build and push
          uses: docker/build-push-action@v2
          env:
              BASE_URL: ${{ secrets.BASE_URL }}
              CLIENT_ID: ${{ secrets.CLIENT_ID }}
              ISSUER_BASE_URL: ${{ secrets.ISSUER_BASE_URL }}
              SECRET: ${{ secrets.SECRET }}
          with:         
              context: ./app
              file: ./app/Dockerfile
              builder: ${{ steps.buildx.outputs.name }}
              push: true
              tags:  ${{ secrets.DOCKER_USERNAME }}/helloworlapi:london
              cache-from: type=local,src=/tmp/.buildx-cache
              cache-to: type=local,dest=/tmp/.buildx-cache
                  
        - name: Image digest 
          
          run: echo ${{ steps.docker_build.outputs.digest }}