name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

      # setup Docker buld action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
          username: ${{ KEYS.DOCKER_USERNAME }}
          password: ${{ KEYS.DOCKER_ACCESS_TOKEN }}

     - name: Build and push
       uses: docker/build-push-action@v2
       with:
          BASE_URL: ${{ KEYS.BASE_URL }}
          CLIENT_ID: ${{ KEYS.CLIENT_ID }}
          ISSUER_BASE_URL: ${{ KEYS.ISSUER_BASE_URL }}
          SECRET: ${{ KEYS.SECRET }}

          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  ${{ KEYS.DOCKER_USERNAME }}/helloworlapi:london
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
               
     - name: Image digest 
       
       run: echo ${{ steps.docker_build.outputs.digest }}
